#pragma once

#define TAPPING_TERM 200
#define TAPPING_FORCE_HOLD

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
    #define RGBLIGHT_DEFAULT_HUE 0
    #define RGBLIGHT_DEFAULT_SAT 0
    #define RGBLIGHT_DEFAULT_VAL 255
#endif
